### PR TITLE
Added support for enabling video front camera mirroring

### PR DESCRIPTION
**Pull request by jensgrud**

### CODE REVIEW

**Comment by rFlex** [comment]
Hey, this looks fine to me. Thank you! Just incase: did you look at the "keepMirroringOnWrite"  property? This will keep the mirroring for previewing for write the buffers at if they were not mirrored, instead of completely removing the mirroring.

**Comment by jensgrud** [comment]
Awesome, glad to hear! Did play around with the "keepMirroringOnWrite" but getting only audio when exporting from front camera. Still debugging here - will let you know how it goes.

**Comment by joshuamanns** [comment]
Hi, has there been any progress on fixing the audio only bug when using keepmirroringonwrite with front camera? Still having that issue using latest build

**Comment by azatZ** [comment]
This property hasn't affect on photo, taken with -capturePhoto method. Maybe configuration video mirroring should contain setting video mirroring on photo output video connection. Correct me if I wrong.

**Pull request merged**
